sudo: required
language: generic
services:
       - docker


before_install:
       - docker build -t ksmk1006/docker-react -f Dockerfile.dev .

script:
     - docker run -e CI=true ksmk1006/docker-react npm run test

