sudo: required
language: generic
services:
       - docker


before_install:
       - docker build -t ksmk1006/docker-react -f Dockerfile.dev .

script:
     - docker run -e CI=true ksmk1006/docker-react npm run test

deploy:
     provider: elasticbeanstalk
     region: "us-east-2"
     app: "docker-react"
     env: "DockerReact-env"
     bucket_name: "elasticbeanstalk-us-east-2-030553554984"
     bucket_path: "docker-react"
     on:
             branch: master

     access_key_id: $access_key_id
     secret_access_key: $secret_access_key
